### ISSUE TITLE
 i reworked it a bit

### ISSUE THREAD

**Issue by jonathan-annett** [jitbit/TabUtils#2]
i won't bother with a pull request, but if you want to borrow some ideas from this

https://s.codepen.io/sophtwhere/debug/pmovgK/yYAyLOQdbwJr

- directed messages with callbacks (and quasi returns)
- every message sent is actually a function being invoked in the other tab/window
- every argument is parsed and functions are sent as tokens, wrapped into callbacks and the arguments are passed to a local function

**Comment by jonathan-annett** [comment]
just noticed if you duplicate a tab  you will need to refresh it before it gets a unique id.
i'll sort that at some point

**Comment by jonathan-annett** [comment]
fixed that issue with duplicate tabs.

**Comment by jonathan-annett** [comment]
moved it to a glitch so i could add a websocket interconnect
https://nebula-pot.glitch.me/
(now also supports promises, although via a few clumsy wrappers)

**Comment by alex-jitbit** [comment]
Sorry, just got my hand on this. Will review your glitch later
